version: '2'
services:
    trackdayman-app:
        image: trackdayman
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://trackdayman-postgresql:5432/trackdayman
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trackdayman-postgresql:
        extends:
            file: postgresql.yml
            service: trackdayman-postgresql
